---
abstract: 'Weave pseudo-POD into real POD'
author:
  - 'Christopher J. Madsen <perl@cjmweb.net>'
generated_by: 'Dist::Zilla version 1.100600'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Loom
requires:
  Carp: 0
  Exporter: 0
  ExtUtils::MakeMaker: 6.11
  Moose: 0.65
  PPI: 0
  Pod::Eventual: 0
  String::RewritePrefix: 0
  perl: 5.8.0
resources:
  repository: http://github.com/madsen/pod-loom
version: 0.03
